export default {
    DATA_STORAGE_IP_ADDRESS: 'DATA_SOTRAGE_IP_ADDRESS',
    DATA_STORAGE_PORT: 'DATA_STORAGE_PORT',
    DATA_STORAGE_REQUEST_METHOD_TYPE: 'DATA_STORAGE_REQUEST_METHOD_TYPE',
    
    JWT_TOKEN_FOR_PERMISSION_REQUESTS_AND_PROFILES: 'JWT_TOKEN_FOR_PERMISSION_REQUESTS_AND_PROFILES',
    VIEW_INSTANCE_TOKEN: 'VIEW_INSTANCE_TOKEN',

    TOKEN_FOR_EVENTS_MANIPULATION: 'TOKEN_FOR_EVENTS_MANIPULATION',

    IS_VIEW_INSTANCE_USED_FOR_EVENTS_FETCHING: 'IS_VIEW_INSTANCE_USED_FOR_EVENTS_FETCHING'
}