export default {
    DATA_STORAGE_IP_ADDRESS: 'DATA_SOTRAGE_IP_ADDRESS',
    DATA_STORAGE_PORT: 'DATA_STORAGE_PORT',
    DATA_STORAGE_REQUEST_METHOD_TYPE: 'DATA_STORAGE_REQUEST_METHOD_TYPE',
    
    JWT_TOKEN_FOR_PERMISSION_REQUESTS_AND_PROFILES: 'JWT_TOKEN_FOR_PERMISSION_REQUESTS_AND_PROFILES',
    VIEW_INSTANCE_TOKEN: 'VIEW_INSTANCE_TOKEN',

    TOKEN_FOR_EVENTS_MANIPULATION: 'TOKEN_FOR_EVENTS_MANIPULATION',

    IS_VIEW_INSTANCE_USED_FOR_EVENTS_FETCHING: 'IS_VIEW_INSTANCE_USED_FOR_EVENTS_FETCHING',

    // windows apps specific [start]
    ARE_WINDOWS_OPENED_APPS_SHOWN: 'ARE_WINDOWS_OPENED_APPS_SHOWN',

    VIEW_INSTANCE_ACCESS_TOEKN_FOR_WINDOWS_OPENED_APPS_UNIQUE_NAMES_LIST: 'VIEW_INSTANCE_ACCESS_TOEKN_FOR_WINDOWS_OPENED_APPS_UNIQUE_NAMES_LIST',
    WINDOWS_APPS_CATEGORIES: 'WINDOWS_APPS_CATEGORIES',
    WINDOWS_APPS_WITH_ASSIGNED_CATEGORIES: 'WINDOWS_APPS_WITH_ASSIGNED_CATEGORIES',
    // windows apps specific [end]

    // android locations specific [start]
    ARE_ANDROID_LOCATIONS_SHOWN: 'ARE_ANDROID_LOCATIONS_SHOWN',
    // android locations specific [end]
}