export const timeConstants = {
    NUMBER_OF_SECONDS_IN_DAY: 86400,
    NUMBER_OF_MINUTES_IN_DAY: 86400 / 60,
    THIRTY_MINUTES_IN_MINUTES: 30,
    ONE_HOUR_IN_MINUTES: 60,
    NUMBER_OF_MILLISECONDS_IN_A_MINUTE: 60000
};