const express = require('express');
const {startDataViewStore} = require('./services/DataViewStoreService');
require('dotenv').config();
const logger = require('./logger/winston');
const { gracefulShutdown } = require('./utils/shutdownManager/shutdownManager');

const dataViewStoreRoutes = require("./routes/dataViewStoreRoutes");

startDataViewStore();

const app = express();

app.use('/api/dataviewstore', dataViewStoreRoutes);

app.listen(process.env.DATA_STORAGE_SERVER_PORT, () => {
    logger.log({
        level: 'info',
        message: `DataStorageServer running on port ${process.env.DATA_STORAGE_SERVER_PORT}!`,
    });
});

process.on('SIGINT', gracefulShutdown); // generated by the user; pressing Ctrl+C
process.on('SIGTERM', gracefulShutdown); // sent programmatically or by system administrators. Often used by process managers, like PM2 or systemd, to stop a process.
// Emitted when the Node.js process is about to exit as a result of either:
// The process.exit() method being called explicitly.
// The Node.js event loop not having any additional work to perform.
process.on('exit', gracefulShutdown);
