const express = require('express');
const multer = require('multer');
const fs = require('fs');
const {v4: uuidv4} = require("uuid");

const { startJavascriptExecutionService } = require('./src/servicesUtils/jsExecutionServiceUtil');
const { gracefulShutdown } = require('./src/shutdown/shutdownUtils');

const registerTemplatesRoutes = require('./src/routes/templatesRelatedRoutes');

const app = express();
app.use(express.json());

const port = 10000;

const db = require('./src/database/Database')
db.connect();

// startJavascriptExecutionService();

const UPLOADS_TEMPORARY_DIRECTORY = './temp_uploads';
const MAXIMUM_UPLOAD_LIMIT_PER_FILE = 1024 * 1024 * 5; // 5 MB
const MAXIMUM_NUMBER_OF_UPLOADED_FILES_PER_REQUEST = 10;

const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        if (!fs.existsSync(UPLOADS_TEMPORARY_DIRECTORY)) {
            fs.mkdirSync(UPLOADS_TEMPORARY_DIRECTORY, { recursive: true });
        }
        cb(null, UPLOADS_TEMPORARY_DIRECTORY)
    },
    filename: function (req, file, cb) {
        cb(null, uuidv4() + '-' + Date.now() + '-' + file.originalname)
    }
});

const uploadMulterMiddleware = multer({ 
    storage: storage,
    fileSize: MAXIMUM_UPLOAD_LIMIT_PER_FILE,
    files: MAXIMUM_NUMBER_OF_UPLOADED_FILES_PER_REQUEST
});


app.use('/', registerTemplatesRoutes(uploadMulterMiddleware))

app.listen(port, () => {
    console.log(`ViewManager listening at http://localhost:${port}`);
});

process.on('SIGINT', gracefulShutdown); // generated by the user; pressing Ctrl+C
process.on('SIGTERM', gracefulShutdown); // sent programmatically or by system administrators. Often used by process managers, like PM2 or systemd, to stop a process.
// Emitted when the Node.js process is about to exit as a result of either:
// The process.exit() method being called explicitly.
// The Node.js event loop not having any additional work to perform.
process.on('exit', gracefulShutdown);
