const express = require('express');

const { startJavascriptExecutionService } = require('./src/servicesUtils/jsExecutionServiceUtil');
const { gracefulShutdown } = require('./src/shutdown/shutdownUtils');

const app = express();
const port = 10000;

startJavascriptExecutionService();

app.get('/', (req, res) => {
    res.send('ViewManager is running. Monitoring JavaScriptExecutionService.');
});

app.listen(port, () => {
    console.log(`ViewManager listening at http://localhost:${port}`);
});

process.on('SIGINT', gracefulShutdown); // generated by the user; pressing Ctrl+C
process.on('SIGTERM', gracefulShutdown); // sent programmatically or by system administrators. Often used by process managers, like PM2 or systemd, to stop a process.
// Emitted when the Node.js process is about to exit as a result of either:
// The process.exit() method being called explicitly.
// The Node.js event loop not having any additional work to perform.
process.on('exit', gracefulShutdown);
